# Import the numpy package under the name np

In [1]:
import numpy as np

# Print the numpy version and the configuration

In [2]:
print(np.__version__)
np.show_config()

1.18.5
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/l/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/l/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/l/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/U

# Create a null vector of size 10 

In [3]:
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


# How to find the memory size of any array 

In [4]:
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


# How to get the documentation of the numpy add function from the command line

# Create a null vector of size 10 but the fifth value which is 1 

In [6]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


# Create a vector with values ranging from 10 to 49

In [7]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


# Reverse a vector (first element becomes last)

In [8]:
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


# Create a 3x3 matrix with values ranging from 0 to 8

In [9]:
Z = np.arange(9).reshape(3, 3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


# Find indices of non-zero elements from [1,2,0,0,4,0]

In [11]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


# Create a 3x3 identity matrix 

In [12]:
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Create a 3x3x3 array with random values

In [13]:
Z = np.random.random((3,3,3))
print(Z)

[[[0.70800968 0.2744674  0.55665728]
  [0.54404886 0.50892164 0.17154822]
  [0.52280568 0.02658138 0.23841544]]

 [[0.38972216 0.45500284 0.33025478]
  [0.48524023 0.34061879 0.79682747]
  [0.38944453 0.44005313 0.91589062]]

 [[0.2942758  0.99178358 0.85817024]
  [0.05933113 0.60126133 0.22093658]
  [0.44245442 0.65116103 0.83202577]]]


# Create a 10x10 array with random values and find the minimum and maximum values

In [15]:
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.017851423838309954 0.9759569300930261


# Create a random vector of size 30 and find the mean value 

In [16]:
Z = np.random.random(30)
m = Z.mean()
print(m)

0.5165888257617736


# Create a 2d array with 1 on the border and 0 inside 

In [17]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


# How to add a border (filled with 0's) around an existing array? 

In [19]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

# Using fancy indexing
Z[:, [0, -1]] = 0
Z[[0, -1], :] = 0
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


# What is the result of the following expression? 

In [22]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


# Create a 5x5 matrix with values 1,2,3,4 just below the diagonal 

In [23]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# Create a 8x8 matrix and fill it with a checkerboard pattern

In [24]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [25]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


# Create a checkerboard 8x8 matrix using the tile function

In [26]:
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# Normalize a 5x5 random matrix 

In [27]:
Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)

[[-1.36459341  1.22950209  1.74138241 -0.36992369  1.00219981]
 [-1.39833544  0.02550712  0.79689153 -0.74389739 -0.34201135]
 [-1.5043468   0.30545438 -1.42183857 -0.90509287  0.07017477]
 [-1.35861979  1.31432637 -0.41895922  0.73317006 -0.15951626]
 [-0.66400819  1.24722354  0.29719083  0.30768197  1.5804381 ]]


# Create a custom dtype that describes a color as four unsigned bytes (RGBA)

In [28]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])

<ipython-input-28-b9f1a6f5df9c>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([("r", np.ubyte, 1),


# Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (

In [30]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

# Alternative solution, in Python 3.5 and above
Z = np.ones((5,3)) @ np.ones((3,2))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]
[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


# Given a 1D array, negate all elements which are between 3 and 8, in place. 

In [31]:
Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


# What is the output of the following script?

In [32]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [33]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


# Consider an integer vector Z, which of these expressions are legal? 

Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z


Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z

# What are the result of the following expressions?

In [37]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

<ipython-input-37-cd809174da5d>:1: RuntimeWarning: invalid value encountered in true_divide
  np.array(0) / np.array(0)
<ipython-input-37-cd809174da5d>:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


array([-2.14748365e+09])

In [38]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


<ipython-input-38-2a10de0ee61b>:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
<ipython-input-38-2a10de0ee61b>:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


# How to round away from zero a float array ?

In [39]:
Z = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(Z)), Z))

# More readable but less efficient
print(np.where(Z>0, np.ceil(Z), np.floor(Z)))

[ 1. -9. -4.  2. -2. -2. -1.  5. 10. -3.]
[ 1. -9. -4.  2. -2. -2. -1.  5. 10. -3.]


# How to find common values between two arrays? (

In [40]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[0 3 8 9]


# How to ignore all numpy warnings (not recommended)? 

In [41]:
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

# Equivalently with a context manager
with np.errstate(all="ignore"):
    np.arange(3) / 0

#  Is the following expressions true? 

In [42]:
np.sqrt(-1) == np.emath.sqrt(-1)
np.sqrt(-1) == np.emath.sqrt(-1)

<ipython-input-42-5947ba3ed4e0>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)
<ipython-input-42-5947ba3ed4e0>:2: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

# How to get the dates of yesterday, today and tomorrow? 

In [43]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)

In [44]:
yesterday

numpy.datetime64('2020-12-31')

In [45]:
today 

numpy.datetime64('2021-01-01')

In [46]:
tomorrow 

numpy.datetime64('2021-01-02')

# How to get all the dates corresponding to the month of July 2016? 

In [47]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


# How to compute ((A+B)*(-A/2)) in place (without copy)?

In [48]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

# Extract the integer part of a random array of positive numbers using 4 different methods

In [49]:
Z = np.random.uniform(0,10,10)

print(Z - Z%1)
print(Z // 1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))

[3. 5. 5. 5. 2. 2. 4. 8. 9. 4.]
[3. 5. 5. 5. 2. 2. 4. 8. 9. 4.]
[3. 5. 5. 5. 2. 2. 4. 8. 9. 4.]
[3 5 5 5 2 2 4 8 9 4]
[3. 5. 5. 5. 2. 2. 4. 8. 9. 4.]


#  Create a 5x5 matrix with row values ranging from 0 to 4 

In [50]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#  Consider a generator function that generates 10 integers and use it to build an array 

In [51]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


# Create a vector of size 10 with values ranging from 0 to 1, both excluded 

In [52]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


# Create a random vector of size 10 and sort it

In [53]:
Z = np.random.random(10)
Z.sort()
print(Z)

[0.09356195 0.18374719 0.18947403 0.21062813 0.2844317  0.32334755
 0.36747248 0.46730752 0.58109534 0.97972063]


# How to sum a small array faster than np.sum?

In [54]:
Z = np.arange(10)
np.add.reduce(Z)

45

# Consider two random array A and B, check if they are equal 

In [55]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)

False
False


# Make an array immutable (read-only) 

# Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates 

In [57]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.71987675 0.51934563 0.39685756 0.58233734 0.43640664 0.94033433
 1.17905871 0.44311233 0.39700802 0.97261598]
[1.39478477 0.15127945 0.27938101 0.27729412 0.71472022 0.08254087
 0.75345677 0.62929185 0.79080365 0.77851693]


# Create random vector of size 10 and replace the maximum value by 0

In [58]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.36774296 0.357667   0.61822069 0.60990908 0.1823699  0.47357173
 0.         0.6553522  0.6581842  0.2862239 ]


# Create a structured array with x and y coordinates covering the [0,1]x[0,1] area 

In [61]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


# Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [60]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.1636371179666


# Print the minimum and maximum representable value for each numpy scalar type

In [62]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


# How to print all the values of an array? 

In [64]:
# np.set_printoptions(threshold=float("inf"))
Z = np.zeros((16,16))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


# How to find the closest value (to a given scalar) in a vector? 

In [65]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

53


#  Create a structured array representing a position (x,y) and a color (r,g,b)

In [66]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


<ipython-input-66-6f1aa4d7a2ff>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  Z = np.zeros(10, [ ('position', [ ('x', float, 1),


# Consider a random vector with shape (100,2) representing coordinates, find point by point distances

In [67]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

# Much faster with scipy
import scipy
# Thanks Gavin Heverly-Coulson (#issue 1)
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.36021821 0.96228845 0.7412501  0.67060352 0.32880325
  0.60081188 0.22861668 0.67232451 0.11054299]
 [0.36021821 0.         0.6231863  0.55311156 0.75118118 0.05041804
  0.31949208 0.49587076 0.40118229 0.40064572]
 [0.96228845 0.6231863  0.         0.88972015 0.99373603 0.63978669
  0.38692283 1.01624008 0.34982736 1.0207326 ]
 [0.7412501  0.55311156 0.88972015 0.         1.29919948 0.5991285
  0.7948453  0.95759664 0.86549377 0.68874013]
 [0.67060352 0.75118118 0.99373603 1.29919948 0.         0.70258143
  0.65833245 0.47246241 0.65639218 0.77918574]
 [0.32880325 0.05041804 0.63978669 0.5991285  0.70258143 0.
  0.31106026 0.44993007 0.39176845 0.38109161]
 [0.60081188 0.31949208 0.38692283 0.7948453  0.65833245 0.31106026
  0.         0.63041637 0.08170002 0.67662707]
 [0.22861668 0.49587076 1.01624008 0.95759664 0.47246241 0.44993007
  0.63041637 0.         0.68377906 0.324395  ]
 [0.67232451 0.40118229 0.34982736 0.86549377 0.65639218 0.39176845
  0.08170002 0.683779

# How to convert a float (32 bits) array into an integer (32 bits) in place?

In [69]:
Z = (np.random.rand(10)*100).astype(np.float32)
Y = Z.view(np.int32)
Y[:] = Z
print(Y)

[61 96 51 72 59 46 54 84 28 49]


# How to read the following file?

1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11

In [70]:
from io import StringIO

# Fake file
s = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
''')
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


# What is the equivalent of enumerate for numpy arrays?

In [71]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


# Generate a generic 2D Gaussian-like array

In [72]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#  How to randomly place p elements in a 2D array? 

In [73]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


# Subtract the mean of each row of a matrix 

In [74]:
X = np.random.rand(5, 10)

# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)

# Older versions of numpy
Y = X - X.mean(axis=1).reshape(-1, 1)

print(Y)

[[-0.24913254  0.3921893  -0.34682796 -0.47780851  0.01268938 -0.23132707
   0.31729591  0.30249821  0.03639923  0.24402406]
 [-0.48994923  0.39962485 -0.32916093 -0.06991531 -0.07244044  0.30320045
   0.2980338   0.28328826 -0.39431455  0.07163311]
 [-0.25086193  0.34176188  0.41837109 -0.2552355   0.10417881 -0.40506074
  -0.08603016  0.04562301 -0.10928606  0.1965396 ]
 [-0.18784056 -0.60147821  0.39238137 -0.05170081  0.22272303 -0.26180141
   0.01553227  0.30563871  0.23038416 -0.06383855]
 [ 0.21917103  0.0205508   0.31674761  0.06564144 -0.29907273 -0.11039586
  -0.4802273   0.06346132  0.15901865  0.04510504]]


# How to sort an array by the nth column? 

In [75]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[8 1 9]
 [0 6 0]
 [7 4 6]]
[[8 1 9]
 [7 4 6]
 [0 6 0]]


# How to tell if a given 2D array has null columns?

In [76]:
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

False


# Find the nearest value from a given value in an array 

In [77]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.4044554209108665


# Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator?

In [78]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


# Create an array class that has a name attribute

In [81]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


# Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [80]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

# Another solution
# Author: Bartosz Telenczuk
np.add.at(Z, I, 1)
print(Z)

[3. 1. 3. 4. 2. 4. 2. 4. 3. 4.]
[5. 1. 5. 7. 3. 7. 3. 7. 5. 7.]


# How to accumulate elements of a vector (X) to an array (F) based on an index list (I)?

In [82]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


# Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors 

In [83]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*256*256 + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(np.unique(I))

[0 1]


# Considering a four dimensions array, how to get sum over the last two axis at once? 

In [84]:
A = np.random.randint(0,10,(3,4,3,4))
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-2,-1))
print(sum)
# solution by flattening the last two dimensions into one
# (useful for functions that don't accept tuples for axis argument)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[70 68 57 42]
 [50 54 43 70]
 [61 55 37 55]]
[[70 68 57 42]
 [50 54 43 70]
 [61 55 37 55]]


# Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset indices?

In [85]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

# Pandas solution as a reference due to more intuitive code
import pandas as pd
print(pd.Series(D).groupby(S).mean())

[0.61492147 0.4556696  0.53623125 0.66125454 0.38391646 0.46941443
 0.43261938 0.57090908 0.3929789  0.50719855]
0    0.614921
1    0.455670
2    0.536231
3    0.661255
4    0.383916
5    0.469414
6    0.432619
7    0.570909
8    0.392979
9    0.507199
dtype: float64


# How to get the diagonal of a dot product? 

In [86]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

# Slow version
np.diag(np.dot(A, B))

# Fast version
np.sum(A * B.T, axis=1)

# Faster version
np.einsum("ij,ji->i", A, B)

array([1.06503183, 0.37206398, 0.8972107 , 2.32854348, 1.56468216])

# Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? 

In [87]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


# Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)?

In [88]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


# How to swap two rows of an array

In [89]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


# Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the triangles

In [90]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 2, 17) ( 2, 41) ( 5, 31) ( 5, 63) ( 8, 57) ( 8, 91) (11, 91) (11, 92)
 (16, 18) (16, 38) (17, 41) (18, 38) (22, 49) (22, 79) (23, 46) (23, 82)
 (31, 63) (31, 87) (31, 92) (38, 81) (38, 85) (45, 50) (45, 72) (46, 82)
 (49, 79) (50, 72) (57, 91) (81, 85) (87, 92) (91, 92)]


# Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C?

In [91]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


# How to compute averages using a sliding window over an array? 

In [92]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


# Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1])

In [93]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


# How to negate a boolean, or to change the sign of a float inplace?

In [94]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([-0.21430197, -0.05549594,  0.77472973,  0.6374603 , -0.92131343,
       -0.38353691,  0.4478684 ,  0.08513475, -0.3829976 ,  0.92307577,
        0.79795086,  0.92324632, -0.49227881, -0.49342923, -0.65328969,
        0.2837144 , -0.93622033,  0.79195628,  0.10737604, -0.17210214,
        0.54806079, -0.81605975,  0.70744122,  0.79979213, -0.88350119,
       -0.59471246,  0.58690745, -0.78127958,  0.53865191, -0.79708467,
        0.20021461,  0.70513333, -0.70996287,  0.27059229, -0.56377768,
       -0.03081297, -0.91056686,  0.00281427,  0.5596067 , -0.27948108,
       -0.14299083,  0.63234795,  0.90931481, -0.81230149,  0.42556726,
       -0.19565576,  0.31920764, -0.65225506, -0.12741115,  0.20638949,
        0.54424154, -0.55392923,  0.96536334, -0.62228984, -0.14256887,
       -0.70015189,  0.59096911,  0.11909797,  0.09837174, -0.832285  ,
        0.5835217 , -0.8267396 , -0.2733075 , -0.46137611,  0.06022384,
       -0.34592644,  0.54577027,  0.96058317, -0.1836568 ,  0.89

# Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])?

In [95]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[12.69644841 13.04104128  4.35984679 12.76378601  9.84383309 13.9793873
  3.68498559  8.84165807 19.64863956  2.17852928]


# Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? 

In [96]:
# based on distance function from previous question
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[11.21715024  6.9892308  15.34429937  6.38319241  1.79621282 11.62315572
   4.10559018  3.80604139  2.61359075  6.96954552]
 [ 1.08126818  8.95506752  9.34352927  3.75578528  4.93956298  4.35451335
   8.09737304  9.88513629  6.50039075  5.70853453]
 [ 2.17142851  1.64535426  0.59732751  7.02116075 14.78795055  5.36784037
   2.30836743  6.10064545 15.17729589  3.32370538]
 [ 8.03814481  7.86335015 13.72220135  3.20359509  0.06706134  9.58311943
   5.58688755  5.89870971  0.058333    6.85388366]
 [ 4.60695101  8.99384238  4.90147561  9.44730817  9.75008472  0.71523304
   9.38980163 12.52787218 12.38620713  3.84432084]
 [ 3.61839797  4.18255842  1.91874344  1.23648984 15.49496673  5.59447106
   4.16097728  0.77018545 13.37949088  7.71544143]
 [ 6.07446291  5.77368527 10.06591461  1.23567784  3.76359002  5.875771
   4.16057556  5.29203741  3.61367864  3.9253191 ]
 [ 6.67684231  3.63944191  8.38617992  1.83527239  5.31622384  4.43027171
   2.12710824  3.47361386  4.53344461  1.80830607]
 [

# Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a fill value when necessary)

In [97]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[4 7 0 1 0 6 8 9 3 7]
 [6 6 2 5 7 1 8 1 6 2]
 [3 5 5 0 7 4 5 2 5 9]
 [3 2 7 7 6 7 2 8 2 8]
 [8 1 8 9 4 7 5 7 2 2]
 [2 9 3 3 8 3 2 1 0 7]
 [3 6 6 8 3 1 0 0 9 4]
 [0 5 4 2 8 5 1 5 4 2]
 [9 8 0 6 8 3 2 8 4 2]
 [5 0 0 6 2 5 0 5 5 5]]
[[0 0 0 0 0]
 [0 4 7 0 1]
 [0 6 6 2 5]
 [0 3 5 5 0]
 [0 3 2 7 7]]


<ipython-input-97-f2b5781f38bf>:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  R[r] = Z[z]


# Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? 

In [98]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


# Compute a matrix rank

In [99]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

10


# How to find the most frequent value in an array?

In [100]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

5


# Extract all the contiguous 3x3 blocks from a random 10x10 matrix 

In [101]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[2 4 2]
   [2 3 0]
   [1 3 1]]

  [[4 2 0]
   [3 0 3]
   [3 1 1]]

  [[2 0 2]
   [0 3 1]
   [1 1 3]]

  [[0 2 0]
   [3 1 1]
   [1 3 2]]

  [[2 0 4]
   [1 1 2]
   [3 2 3]]

  [[0 4 1]
   [1 2 2]
   [2 3 1]]

  [[4 1 2]
   [2 2 0]
   [3 1 2]]

  [[1 2 1]
   [2 0 3]
   [1 2 4]]]


 [[[2 3 0]
   [1 3 1]
   [4 2 4]]

  [[3 0 3]
   [3 1 1]
   [2 4 3]]

  [[0 3 1]
   [1 1 3]
   [4 3 0]]

  [[3 1 1]
   [1 3 2]
   [3 0 1]]

  [[1 1 2]
   [3 2 3]
   [0 1 1]]

  [[1 2 2]
   [2 3 1]
   [1 1 0]]

  [[2 2 0]
   [3 1 2]
   [1 0 4]]

  [[2 0 3]
   [1 2 4]
   [0 4 3]]]


 [[[1 3 1]
   [4 2 4]
   [0 4 2]]

  [[3 1 1]
   [2 4 3]
   [4 2 3]]

  [[1 1 3]
   [4 3 0]
   [2 3 4]]

  [[1 3 2]
   [3 0 1]
   [3 4 2]]

  [[3 2 3]
   [0 1 1]
   [4 2 4]]

  [[2 3 1]
   [1 1 0]
   [2 4 1]]

  [[3 1 2]
   [1 0 4]
   [4 1 4]]

  [[1 2 4]
   [0 4 3]
   [1 4 1]]]


 [[[4 2 4]
   [0 4 2]
   [4 4 4]]

  [[2 4 3]
   [4 2 3]
   [4 4 1]]

  [[4 3 0]
   [2 3 4]
   [4 1 2]]

  [[3 0 1]
   [3 4 2]
   [1 2 3]]

  [[0 1 1]
   

# Create a 2D array subclass such that Z[i,j] == Z[j,i] 

In [102]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 9  7  1 14  2]
 [ 7  4 10 12 14]
 [ 1 10  2 42 13]
 [14 12 42  3  7]
 [ 2 14 13  7  4]]


# Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1))

In [104]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)
# It works, because:
# M is (p,n,n)
# V is (p,n,1)
# Thus, summing over the paired axes 0 and 0 (of M and V independently),
# and 2 and 1, to remain with a (n,1) vector.

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


# Consider a 16x16 array, how to get the block-sum (block size is 4x4)?

In [105]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


# How to implement the Game of Life using numpy arrays? 

In [106]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 1 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  1 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 1 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 1 1 0 0 0
  1 0 1 0 0 0 0 0 1 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 1 1 0 0 0
  0 1 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 1 0 0 0 0 1 1 0 0]
 [0 0 0 0 0 0 0 0 1 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 1 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 1 1 1 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  1 0 0 1 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0

# How to get the n largest values of an array

In [107]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])

# Fast
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9999 9998 9996 9997 9995]


# Given an arbitrary number of vectors, build the cartesian product (every combinations of every item)

In [111]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


# How to create a record array from a regular array? 

In [114]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


# Consider a large vector Z, compute Z to the power of 3 using 3 different methods

In [113]:
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

1.82 s ± 9.03 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
408 ms ± 3.68 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
251 ms ± 2.56 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


# Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B?

In [115]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[1 3 5 6 7]


# Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) 

In [116]:
Z = np.random.randint(0,5,(10,3))
print(Z)
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)
# soluiton for numerical arrays only, will work for any number of columns in Z
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[3 3 1]
 [4 0 1]
 [0 4 3]
 [1 3 2]
 [1 4 3]
 [4 1 3]
 [1 3 0]
 [2 1 2]
 [1 1 0]
 [1 4 1]]
[[3 3 1]
 [4 0 1]
 [0 4 3]
 [1 3 2]
 [1 4 3]
 [4 1 3]
 [1 3 0]
 [2 1 2]
 [1 1 0]
 [1 4 1]]
[[3 3 1]
 [4 0 1]
 [0 4 3]
 [1 3 2]
 [1 4 3]
 [4 1 3]
 [1 3 0]
 [2 1 2]
 [1 1 0]
 [1 4 1]]


# Convert a vector of ints into a matrix binary representation

In [117]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

# Author: Daniel T. McDonald

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


# Given a two dimensional array, how to extract unique rows?

In [118]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

# Author: Andreas Kouzelis
# NumPy >= 1.13
uZ = np.unique(Z, axis=0)
print(uZ)

[[0 0 1]
 [0 1 0]
 [1 0 0]
 [1 0 1]
 [1 1 0]]
[[0 0 1]
 [0 1 0]
 [1 0 0]
 [1 0 1]
 [1 1 0]]


# Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function

In [119]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[0.00862179, 0.10154051, 0.05095231, 0.09329623, 0.11511337,
        0.02033453, 0.14617164, 0.10319636, 0.04133323, 0.04184105],
       [0.02887054, 0.34001396, 0.17061659, 0.31240754, 0.38546341,
        0.06809129, 0.48946373, 0.34555865, 0.13840658, 0.14010704],
       [0.04106493, 0.4836296 , 0.24268189, 0.44436272, 0.54827605,
        0.09685179, 0.69620419, 0.49151626, 0.19686697, 0.19928568],
       [0.05752649, 0.67750062, 0.33996499, 0.62249296, 0.76806169,
        0.13567646, 0.9752893 , 0.68854878, 0.27578439, 0.27917268],
       [0.04972658, 0.58563954, 0.29386976, 0.53809027, 0.6639216 ,
        0.11728033, 0.8430516 , 0.59518971, 0.23839128, 0.24132016],
       [0.04673932, 0.55045809, 0.27621595, 0.50576527, 0.62403747,
        0.11023488, 0.79240648, 0.55943454, 0.22407027, 0.2268232 ],
       [0.05426499, 0.63908933, 0.32069048, 0.58720037, 0.72451599,
        0.1279842 , 0.91999471, 0.64951111, 0.26014863, 0.26334482],
       [0.05647204, 0.66508219, 0.3337335

# Considering a path described by two vectors (X,Y), how to sample it using equidistant samples 

In [120]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

# Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n.

In [121]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


# Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means).

In [122]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.23897178  0.11259261]
