# NUMPY
Numpy library is  the core library  for scientific computing  in python.It provides a high-performance multidimensional array object, and tools for working with these arrays.

In [1]:
import numpy as np

# creating arrays


In [2]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
a=np.array([1,2,3]),([4,5,6])

In [4]:
print(a)
print(type(a))

(array([1, 2, 3]), [4, 5, 6])
<class 'tuple'>


In [5]:
b = np.array([(1.5,2,3), (4,5,6)], dtype = float)
c = np.array([[(1.5,2,3), (4,5,6)], [(3,2,1), (4,5,6)]],
dtype = float)
print(b)
print(c)

[[1.5 2.  3. ]
 [4.  5.  6. ]]
[[[1.5 2.  3. ]
  [4.  5.  6. ]]

 [[3.  2.  1. ]
  [4.  5.  6. ]]]


In [6]:
a=np.array([1,2,3])
#type of an array
type(a)

numpy.ndarray

In [7]:
b=np.array((1,2,3)) #tuple

In [8]:
print(a)
print(b)

[1 2 3]
[1 2 3]


In [9]:
c= np.array([[1,2,3], [3,4]])
c
c[0][0]

1

In [10]:
c.shape

(2,)

In [11]:
np.array([4,5,6,7],ndmin= 20)

array([[[[[[[[[[[[[[[[[[[[4, 5, 6, 7]]]]]]]]]]]]]]]]]]]])

In [12]:
np.array([4,5,6,7] , dtype = complex)

array([4.+0.j, 5.+0.j, 6.+0.j, 7.+0.j])

In [13]:
np.array([(3,4) , (5,6)])

array([[3, 4],
       [5, 6]])

In [14]:
n = np.array([(3,4) , (5,6)],dtype = [('a' , '<i4'),('b' , '<i2')])
type(n[0][0])

numpy.int32

In [15]:
type(n[0][1])

numpy.int16

In [16]:
m = np.mat([1,2,3,4])
m

matrix([[1, 2, 3, 4]])

In [17]:
np.array([5,6,7,7])
np.array(m)

array([[1, 2, 3, 4]])

In [18]:
np.asanyarray([5,6,7,78])
np.asanyarray(m)

matrix([[1, 2, 3, 4]])

In [19]:
np.fromfunction(lambda x,y : x==y , (3,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False]])

In [20]:
np.fromfunction(lambda x,y : x - y*6 , (3,4))

array([[  0.,  -6., -12., -18.],
       [  1.,  -5., -11., -17.],
       [  2.,  -4., -10., -16.]])

In [21]:
np.fromstring('6,7', dtype = int ,sep= ',')

array([6, 7])

In [22]:
a = [[3,4,5] ,[6,7,8] ,[6,7,9]]
n = np.array(a)
n


array([[3, 4, 5],
       [6, 7, 8],
       [6, 7, 9]])

In [23]:
print(n.ndim)
print(n.size)
print(n.shape)
print(n.dtype)


2
9
(3, 3)
int32


In [24]:
m = np.array([])
m.ndim


1

# Initial Placeholders


In [25]:
#to initialize  an array of xyz dimension with 0
import numpy as np
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [26]:
#Create an array of ones
np.ones((2,3,4),dtype=np.int16) 

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [27]:
np.logspace(5.6 , 7.8 ,6 ,base=2)

array([ 48.50293013,  65.79928491,  89.26359465, 121.09537878,
       164.27851489, 222.8609442 ])

In [28]:
 #Create an array of evenly
d = np.arange(10,25,5)  #spaced values (step value)
d

array([10, 15, 20])

In [29]:
#arranging numbers between x and y with an interval of z
#print based on intervals it takes start no,end no and interval
import numpy as np
a=np.arange(10,19,2)
print(a)

[10 12 14 16 18]


In [30]:
#to spread in st.line   #Create an array of evenly
import numpy as np
np.linspace(5,10,6)

array([ 5.,  6.,  7.,  8.,  9., 10.])

In [31]:
np.linspace(0,2,9) #spaced values(number of samples)


array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [32]:
#linspace start no end no  v wl get points
import numpy as np
np.linspace(5,10,5)

array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [33]:
import numpy as np
np.linspace(0,10,6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [34]:
#2row 2 col full function
#create a constant array
import numpy as np
np.full((2,2),5)

array([[5, 5],
       [5, 5]])

In [35]:
import numpy as np
np.full((2,4),6)

array([[6, 6, 6, 6],
       [6, 6, 6, 6]])

In [36]:
#Create a 2X2 identity matrix
f = np.eye(2)
f

array([[1., 0.],
       [0., 1.]])

In [37]:
#filling random numbers
import numpy as np
np.random.random((2,2))

array([[0.14859007, 0.86978967],
       [0.49766141, 0.5209026 ]])

In [38]:
#Create an empty array
np.empty((3,2))

array([[ 0.,  2.],
       [ 4.,  6.],
       [ 8., 10.]])

# Saving & Loading On Disk


In [39]:
np.save('my_array', a)

In [40]:
np.savez('array.npz', a, b)


In [41]:
np.load('my_array.npy')

array([10, 12, 14, 16, 18])

# Saving & Loading Text Files

In [42]:
np.loadtxt("myfile.txt")
#np.genfromtxt("my_file.csv", delimiter=',')
#np.savetxt("myarray.txt", a, delimiter=" ")


array([1., 2., 3., 4., 5.])

# DATATYPES

In [43]:
print(np.int64 )  #Signed 64-bit integer types
print(np.float32 )  #Standard double-precision floating point
print(np.complex)  #Complex numbers represented by 128 floats
print(np.bool)        #Boolean type storing TRUE and FALSE values
print(np.object )   #Python object type
print(np.string_) # Fixed-length string type
print(np.unicode_)   #Fixed-length unicode type

<class 'numpy.int64'>
<class 'numpy.float32'>
<class 'complex'>
<class 'bool'>
<class 'object'>
<class 'numpy.bytes_'>
<class 'numpy.str_'>


# Inspecting Your Array

In [44]:
#resize the array ndarray.shape
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print(a)
print(a.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [45]:
#to change the shape
a.shape=(3,2)
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [46]:
#resizes the ndarray
import numpy as np
a=np.array([[1,2,3,4],[4,5,6,7]])
a.shape=(8,1)
print(a)
#length of array
len(a)

[[1]
 [2]
 [3]
 [4]
 [4]
 [5]
 [6]
 [7]]


8

In [47]:
a=np.array([[1,2,3,4],[4,5,6,7]])
a.ndim    #Number of array dimensions

2

In [48]:
#to get total no columns
a=np.arange(24)
a.size
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [49]:
#returns datatype of an array
import numpy as np
a=np.arange(24,dtype=float)
#Number of array elements
print (a.size)
#Data type of array elements
print(a.dtype)
#Name of data type
a.dtype.name 
b=a.reshape(3,4,2)
b

24
float64


array([[[ 0.,  1.],
        [ 2.,  3.],
        [ 4.,  5.],
        [ 6.,  7.]],

       [[ 8.,  9.],
        [10., 11.],
        [12., 13.],
        [14., 15.]],

       [[16., 17.],
        [18., 19.],
        [20., 21.],
        [22., 23.]]])

In [50]:
#Convert an array to a different type
a.astype(int) 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [51]:
#Asking For Help
np.info(np.ndarray.dtype)

Data-type of the array's elements.

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>


# ARITHMETIC OPERATIONS

In [52]:
#linear algebra
#addition using numpy
import numpy as np
print(np.sum([10,20]))
#OR
a,b=10,20
print(np.sum([a,b]))

30
30


In [53]:
np.sum([[0,1],[0,5]],axis=0)

array([0, 6])

In [54]:
np.sum([[0,1],[0,5]],axis=1)

array([1, 5])

In [55]:
b=np.array([2,3])
print(b)
print(np.sum([a,b]))
print(np.subtract(a,b))

[2 3]
[12 13]
[8 7]


In [56]:
np.sum([[a,b]],axis=0)


array([10, array([2, 3])], dtype=object)

In [57]:
#Subtraction
np.subtract(a,b)

array([8, 7])

In [58]:
#division
np.divide(a,b)

array([5.        , 3.33333333])

In [59]:
#Multiplication
np.multiply(a,b)

array([20, 30])

In [60]:
#exponentation
np.exp(a)

22026.465794806718

In [61]:
#Square root
np.sqrt(a)

3.1622776601683795

In [62]:
#Print sines of an array
np.sin(a)

-0.5440211108893698

In [63]:
#Element-wise cosine
np.cos(a) 

-0.8390715290764524

In [64]:
#Element-wise natural logarithm
np.log(a)

2.302585092994046

In [65]:
a=np.array([5,10])
print(a)
np.sum(a)

[ 5 10]


15

In [66]:
#element wise comparison
a=[1,2,3]
b=[2,4,3]
np.equal(a,b)

array([False, False,  True])

In [67]:
#array wise comparison
import numpy as np
a=[1,2,4]
b=[2,4,4]
c=[1,2,4]
d=np.array_equal(a,c)
e=np.array_equal(a,b)
print(d)
print(e)


True
False


In [68]:
#numpy aggegrate functions
import numpy as np
a=[1,2,4]
print(np.sum(a))  #array wise sum
print(np.min(a))  #min of an array
print(np.max(a)) #max of an array
print(np.mean(a)) # mean of an array
print(np.median(a)) #median of an array
print(np.corrcoef(a)) #correlation coefficient of array
print(np.std(a)) #standard deviation of array


7
1
4
2.3333333333333335
2.0
1.0
1.247219128924647


# COPYING ARRAYS

In [69]:
#Create a view of the array with the same data
a=np.array([1,2,3])
h = a.view() 
#Create a copy of the array
np.copy(a)
#Create a deep copy of the array
h = a.copy() 
h

array([1, 2, 3])

# Sorting arrays

In [70]:
#Sort an array
a=np.array([1,3,2])
a.sort() 
a
#Sort the element of an array axis
#c.sort(axis=0) 

array([1, 2, 3])

# subsetting

In [71]:
#Subsetting
a=np.array([[0,0,0],[10,10,10],[20,20,20],[30,30,30]])
b=np.array([0,1,2])
#Select the element at the 2nd index
a[2] 

array([20, 20, 20])

In [72]:
#Select the element at row 1 column 2
a[1,2] 

10

In [73]:
#Slicing
#Select items at index 0 and 1
a[0:2] 

array([[ 0,  0,  0],
       [10, 10, 10]])

In [74]:
#Select items at rows 0 and 1 in column 1
a[0:2,1] 

array([ 0, 10])

In [75]:
#Select all items at row 0
b[:1] 
a[1,...] #Same as [1,:,:]

array([10, 10, 10])

In [76]:
# Reversed array a
a[ : :-1]

array([[30, 30, 30],
       [20, 20, 20],
       [10, 10, 10],
       [ 0,  0,  0]])

In [77]:
#Boolean Indexing
#Select elements from a less than 2
a[a<2] 

array([0, 0, 0])

In [78]:
#Fancy Indexing
#Select elements (1,0),(0,1),(1,2) and (0,0)
a[[1, 0, 1, 0],[0, 1, 2, 0]] 

array([10,  0, 10,  0])

In [79]:
#Select a subset of the matrix’s rows
a[[1, 0, 1, 0]][:,[0,1,2,0]] 

array([[10, 10, 10, 10],
       [ 0,  0,  0,  0],
       [10, 10, 10, 10],
       [ 0,  0,  0,  0]])

# ARRAY MANIPULATION

In [80]:
#Transposing Array
#Permute array dimensions
a=np.array([[0,0,0],[10,10,10],[20,20,20],[30,30,30]])
i = np.transpose(a) 
print(i)
#Permute array dimensions
print(i.T )

[[ 0 10 20 30]
 [ 0 10 20 30]
 [ 0 10 20 30]]
[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]


In [81]:
#Changing Array Shape
#Flatten the array
a.ravel()  
g=np.array([])
#Reshape, but don’t change data
g.reshape(3,-2) 
#Adding/Removing Elements
#Return a new array with shape (2,6)
h=np.array([])
h.resize((2,6)) 
#Append items to an array
np.append(h,g) 
#Insert items in an array
np.insert(a, 1, 5) 
#Delete items from an array
np.delete(a,[1]) 


array([ 0,  0, 10, 10, 10, 20, 20, 20, 30, 30, 30])

# COMBINNING & SPLITTING OF AN ARRAY

In [82]:
#indexing and slicing 
#array manipulation
#concatenating two arrays together
a=[1,2,3]
b=[4,5,6]
np.concatenate((a,b),axis=0)

array([1, 2, 3, 4, 5, 6])

In [83]:
#stack arrays row wise (vertically)
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [84]:
#stack arrays row wise (vertically)
np.hstack((a,b))


array([1, 2, 3, 4, 5, 6])

In [85]:
#combining columnwise stacked array
np.column_stack((a,b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [86]:
#numpy broadcasting
#work only for array addition ,gets inflated to match wit the ndim array
import numpy as np
a=np.array([[0,0,0],[10,10,10],[20,20,20],[30,30,30]])
b=np.array([0,1,2])
print('first array:\n',a,'\n')
print('second array:\n',b,'\n')

print('first array'+ 'second array \n',a+b)
      


first array:
 [[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]] 

second array:
 [0 1 2] 

first arraysecond array 
 [[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]
